async function loadGLB(url, onP) {
  const r = await fetch(url); if(!r.ok) throw new Error("Modelo indisponível"); const total = +r.headers.get("content-length") || 0;
  const rd = r.body.getReader(), parts = []; let got = 0;
  for (;;) { const { done, value } = await rd.read(); if (done) break; parts.push(value); got += value.length; onP(got, total); }
  const all = new Uint8Array(got); let o = 0; for (const p of parts) { all.set(p, o); o += p.length; }
  const buf = all.buffer, dv = new DataView(buf), jl = dv.getUint32(12, true), j = JSON.parse(new TextDecoder().decode(new Uint8Array(buf, 20, jl))), bin = 20 + jl + 8;
  const acc = i => { const a = j.accessors[i], bv = j.bufferViews[a.bufferView], n = { SCALAR: 1, VEC2: 2, VEC3: 3 }[a.type], A = { 5126: Float32Array, 5125: Uint32Array, 5123: Uint16Array }[a.componentType], off = bin + (bv.byteOffset || 0) + (a.byteOffset || 0); return new A(buf.slice(off, off + a.count * n * A.BYTES_PER_ELEMENT)); };
  const out = {}; j.nodes.forEach(nd => { if (nd.mesh === undefined) return; const p = j.meshes[nd.mesh].primitives[0]; out[nd.name] = { pos: acc(p.attributes.POSITION), nor: p.attributes.NORMAL !== undefined ? acc(p.attributes.NORMAL) : null, idx: p.indices !== undefined ? acc(p.indices) : null }; });
  return out;
}

// Geometria, leitor GLB e projeção por raio derivados da home v2 do próprio projeto.
export async function createHeart(o){
 let renderer;
 try{
  const test=document.createElement('canvas');const gl=test.getContext('webgl2');if(!gl)throw new Error('Sem WebGL');gl.getExtension('WEBGL_lose_context')?.loseContext();
  const [T,glb]=await Promise.all([import('three'),loadGLB(o.model,o.onProgress)]);if(!o.isCurrent())return null;
  renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.domElement.setAttribute('aria-hidden','true');o.map.prepend(renderer.domElement);
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(30,1,.1,100);camera.position.set(0,0,13);const root=new T.Group(),heart=new T.Group();scene.add(root);root.add(heart);
  const css=token=>getComputedStyle(document.documentElement).getPropertyValue(token).trim(),center=new T.Vector3(.0187,.4761,.0376),scale=4.6/.1244;
  const fresnel=(base,rim)=>new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{base:{value:new T.Color(css(base))},rim:{value:new T.Color(css(rim))}},vertexShader:'varying vec3 N;varying vec3 V;void main(){vec4 p=modelViewMatrix*vec4(position,1.);N=normalize(normalMatrix*normal);V=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 base;uniform vec3 rim;varying vec3 N;varying vec3 V;void main(){float f=pow(1.-max(dot(normalize(N),normalize(V)),0.),2.1);float key=max(dot(normalize(N),normalize(vec3(-.4,.7,.6))),0.);gl_FragColor=vec4(base*(.35+.65*key)+rim*f, .25+.53*f);}'});
  const mesh=(name,mat)=>{const d=glb[name];if(!d)return null;const g=new T.BufferGeometry(),p=d.pos.slice();for(let i=0;i<p.length;i+=3){p[i]=(p[i]-center.x)*scale;p[i+1]=(p[i+1]-center.y)*scale;p[i+2]=(p[i+2]-center.z)*scale;}g.setAttribute('position',new T.BufferAttribute(p,3));if(d.idx)g.setIndex(new T.BufferAttribute(d.idx,1));if(d.nor)g.setAttribute('normal',new T.BufferAttribute(d.nor,3));else g.computeVertexNormals();g.computeBoundingBox();const c=g.boundingBox.getCenter(new T.Vector3());g.translate(-c.x,-c.y,-c.z);const m=new T.Mesh(g,mat);m.position.copy(c);heart.add(m);return m;};
  const atria=['VH_M_left_cardiac_atrium','VH_M_right_cardiac_atrium'].map(n=>mesh(n,fresnel('--atrium','--violet'))).filter(Boolean),ventr=['VH_M_heart_left_ventricle','VH_M_heart_right_ventricle','VH_M_interventricular_septum'].map(n=>mesh(n,fresnel('--ventricle','--flow'))).filter(Boolean);
  const valves=['VH_M_mitral_valve','VH_M_tricuspid_valve','VH_M_aortic_valve','VH_M_pulmonary_valve'].map(n=>mesh(n,new T.MeshBasicMaterial({color:css('--valve'),transparent:true,opacity:.17,depthWrite:false}))).filter(Boolean);
  heart.updateMatrixWorld(true);const ray=new T.Raycaster(),surf=[...atria,...ventr],ctr=new T.Vector3(.1,-.2,0);
  const surface=(az,el)=>{const a=T.MathUtils.degToRad(az),e=T.MathUtils.degToRad(el),d=new T.Vector3(Math.sin(a)*Math.cos(e),Math.sin(e),Math.cos(a)*Math.cos(e));ray.set(ctr.clone().addScaledVector(d,12),d.clone().negate());const h=ray.intersectObjects(surf,false)[0];return h?h.point.addScaledVector(h.face.normal.clone().transformDirection(h.object.matrixWorld),.045):null;};
  const ends=o.modules.map((m,i)=>{const pts=[];for(let k=0;k<m.path.length-1;k++)for(let s=0;s<9;s++){const t=s/8,a=m.path[k],b=m.path[k+1],p=surface(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t);if(p)pts.push(p);}if(pts.length<4)return null;const curve=new T.CatmullRomCurve3(pts),mat=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{col:{value:new T.Color(css(m.token))},flow:{value:-1},off:{value:o.filled[i]?0:1},hot:{value:0}},vertexShader:'varying vec2 UV;void main(){UV=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 col;uniform float flow;uniform float off;uniform float hot;varying vec2 UV;void main(){if(off>.5){if(fract(UV.x*24.)>.45)discard;gl_FragColor=vec4(col,.4);return;}float p=exp(-pow((UV.x-flow)*10.,2.));gl_FragColor=vec4(col*(1.+hot*.18)+vec3(.8,.4,.5)*p,.95);}'});const tube=new T.Mesh(new T.TubeGeometry(curve,90,.028,7,false),mat);tube.renderOrder=3;heart.add(tube);return{curve,mat,tip:curve.getPoint(1),index:i};});
  let destroyed=false,visible=true,intersecting=true,paused=false,frame=0,timer=null,beatTl=null;const tweens=new Set(),r={x:0,y:0};let frames=0;
  const canDraw=()=>!destroyed&&visible&&intersecting&&!document.hidden;
  const project=()=>{const w=o.map.clientWidth,h=o.map.clientHeight;heart.updateMatrixWorld(true);const points=ends.map(e=>{if(!e)return null;const p=heart.localToWorld(e.tip.clone()).project(camera);return{x:(p.x*.5+.5)*w,y:(-p.y*.5+.5)*h};});o.onProject(points);};
  const draw=()=>{frame=0;if(!canDraw())return;root.rotation.set(r.y,r.x,0);renderer.render(scene,camera);project();frames++;};
  const request=()=>{if(!frame&&canDraw())frame=requestAnimationFrame(draw);};
  const run=(target,vars)=>{if(!window.gsap){Object.assign(target,vars);request();return;}window.gsap.killTweensOf(target);tweens.add(target);window.gsap.to(target,{...vars,overwrite:true,onUpdate:request,onComplete:()=>tweens.delete(target)});};
  const resize=()=>{if(!o.map.clientWidth||!o.map.clientHeight)return;const w=o.map.clientWidth,h=o.map.classList.contains('rail')?o.map.clientHeight-90:o.map.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();const vw=2*13*Math.tan(T.MathUtils.degToRad(15))*camera.aspect;heart.scale.setScalar(Math.min(1.2,vw*.66/4.6));heart.rotation.set(.1,-.12,.035);heart.position.set(0,.25,0);request();};
  function beat(strength=.45,only=null){if(paused||!canDraw()||!window.gsap)return;beatTl?.kill();for(const m of [...atria,...ventr]){window.gsap.killTweensOf(m.scale);m.scale.setScalar(1);}ends.forEach(e=>{if(e)e.mat.uniforms.flow.value=-1;});beatTl=window.gsap.timeline({onUpdate:request});atria.forEach(a=>beatTl.to(a.scale,{x:1-.05*strength,y:1-.05*strength,z:1-.05*strength,duration:.12},0).to(a.scale,{x:1,y:1,z:1,duration:.35},.12));ventr.forEach(v=>beatTl.to(v.scale,{x:1-.065*strength,y:1-.065*strength,z:1-.065*strength,duration:.14},.16).to(v.scale,{x:1,y:1,z:1,duration:.5,ease:'elastic.out(1,.6)'},.3));ends.forEach((e,i)=>{if(e&&o.filled[i]&&(only===null||only===i))beatTl.fromTo(e.mat.uniforms.flow,{value:-.1},{value:1.15,duration:1.1,ease:'power1.in'},.28);});}
  function stop(){clearTimeout(timer);timer=null;beatTl?.pause();if(frame)cancelAnimationFrame(frame);frame=0;}
  function schedule(){clearTimeout(timer);if(!canDraw()||paused)return;timer=setTimeout(()=>{beat();schedule();},2600);}
  const visibility=()=>{if(!canDraw()){stop();}else{beatTl?.resume();request();schedule();}};
  const observer=new IntersectionObserver(es=>{intersecting=es[0].isIntersecting;visibility();});observer.observe(o.map);const ro=new ResizeObserver(resize);ro.observe(o.map);document.addEventListener('visibilitychange',visibility);
  const pointer=e=>{if(paused||!canDraw()||e.pointerType==='touch')return;const b=o.map.getBoundingClientRect();run(r,{x:((e.clientX-b.left)/b.width-.5)*.24,y:((e.clientY-b.top)/b.height-.5)*.12,duration:.5,ease:'power2.out'});};o.map.addEventListener('pointermove',pointer);
  const contextLost=e=>{e.preventDefault();api.dispose();o.onFail();o.map.classList.remove('ready');};renderer.domElement.addEventListener('webglcontextlost',contextLost);
  const api={resize,highlight(i,on){const e=ends[i];if(!e)return;run(e.mat.uniforms.hot,{value:on?1:0,duration:.18});if(on&&o.filled[i])beat(.8,i);},pause(p){paused=p;if(p){stop();beatTl?.kill();[...atria,...ventr].forEach(m=>m.scale.setScalar(1));ends.forEach(e=>{if(e)e.mat.uniforms.flow.value=-1;});request();}else schedule();},visible(v){visible=v;visibility();},theme(){atria.forEach(m=>{m.material.uniforms.base.value.set(css('--atrium'));m.material.uniforms.rim.value.set(css('--violet'));});ventr.forEach(m=>{m.material.uniforms.base.value.set(css('--ventricle'));m.material.uniforms.rim.value.set(css('--flow'));});valves.forEach(m=>m.material.color.set(css('--valve')));ends.forEach((e,i)=>e?.mat.uniforms.col.value.set(css(o.modules[i].token)));request();},update(filled){o.filled=filled;ends.forEach((e,i)=>{if(e)e.mat.uniforms.off.value=filled[i]?0:1;});request();},dispose(){destroyed=true;stop();beatTl?.kill();tweens.forEach(t=>window.gsap?.killTweensOf(t));observer.disconnect();ro.disconnect();document.removeEventListener('visibilitychange',visibility);o.map.removeEventListener('pointermove',pointer);renderer.domElement.removeEventListener('webglcontextlost',contextLost);scene.traverse(n=>{n.geometry?.dispose();n.material?.dispose();});renderer.dispose();renderer.domElement.remove();},get frames(){return frames}};
  resize();o.onReady();request();schedule();return api;
 }catch(e){renderer?.dispose();renderer?.domElement.remove();if(o.isCurrent())o.onFail();return null;}
}


